name: deploy

on:
  workflow_run:
    workflows: [ci]
    types:
      - completed

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [18]

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@master

      - name: Setup node env 🏗
        uses: actions/setup-node@v4.0.4
        with:
          node-version: ${{ matrix.node }}
          check-latest: true
          cache: 'npm'

      - name: Install dependencies 🚀
        run: npm ci --prefer-offline --no-audit

      - name: Generate static site 🐛
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
